#!/usr/bin/env bash

set -e

acbuildend () {
  export EXIT=$?;
  acbuild --debug end && exit $EXIT;
}

acbuild --debug begin
trap acbuildend EXIT


source .env

#TODO: auto-checkpoint after each build.d step
for FILE in build.d/*; do
  source "${FILE}"
done

mkdir -p images/
acbuild --debug write --overwrite images/${IMAGE_NAME}-${IMAGE_VERSION}-${IMAGE_OS}-${IMAGE_ARCH}.aci
